### PR TITLE
Arabic Translation MoveMessage

### PR DESCRIPTION
**Pull request by alhitary**

### CODE REVIEW

**Comment by Elsensee** [comment]
I guess you've translated the english language file, haven't you?

**Comment by alhitary** [comment]
I don't think so because i created ar directory and i see it now : language/ar/movemessage.php
It is language/ar/movemessage.php in files changed
Anyway, I'll re-folk again and PR

**Comment by Elsensee** [comment]
No, sorry, I didn't mean that.
It's because we have an error in our english language file. We will tell you when that error has fixed (it's just 3 and 4 swapped in.. I think..)

**Comment by Elsensee** [comment]
Yeah, as I said, @alhitary. You have to swap %3$s and %4$s and then everything's fine if you translated it from english. :)

**Comment by alhitary** [comment]
Yes
I translated from English file as i don't know other lang

**Comment by gn36** [comment]
Never Mind, since there is another translation comming from english, we will simply swap the options in PHP so your translations stay correct.

**Comment by Crizz0** [comment]
So your translation is still fitting to the english-language file?

**Comment by Elsensee** [comment]
I guess so, it wasn't changed after the comment. ;)

**Comment by alhitary** [comment]
Yes
It is fitting to the English lang. file

**Pull request merged**
