### PR TITLE
Incorporate corrections from phpBB.com Extensions-Team

### PR DESCRIPTION
**Pull request by gn36**
- Typecast int
- rename $result2 to $result
- Typo in README.md

### CODE REVIEW

**Comment by nickvergessen** [comment]
:+1:

**Comment by Crizz0** [comment]
I travis still working or is he stucked?

**Comment by nickvergessen** [comment]
Travis has a status problem since two days and is still recovering

**Comment by Crizz0** [comment]
So i'll keep waiting.

**Pull request merged**
