### PR TITLE
et translation for movemessage.php

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by gn36** [comment]
Did you translate this from English? 
We'll swap option orders because PHP and English were not consistent. If you translated from english, everything is fine, but otherwise your parameter order will be wrong.

**Comment by ghost** [comment]
Yes, translated from English.

**Comment by ghost** [comment]
Can you make changes:

See postitus on liigutatud <strong>%1$s</strong> foorumist <strong>%2$s</strong> foorumisse liikme <strong>%4$s</strong> poolt %3$s.

I deleted forked repo, and i quess i cant anymore edit :S

**Comment by Crizz0** [comment]
Just close this PR and send uns another one. :)

**Comment by ghost** [comment]
OK.

**Pull request closed without merging**
